version: '2'
services:
  jhscratch-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/jhscratch/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhscratch
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
